### ISSUE TITLE
Totally broken latest master UPBGE

### ISSUE THREAD

**Issue by ondredeniso** [UPBGE/blender#349]
Error: cont1(MAPCHANGER), Python script error
Traceback (most recent call last):
  File "D:\Blender Foundation\mygame.blend\Doors.py", line 2185, in SetPosMAPS
AttributeError: 'PyObjectPlus' object has no attribute 'addObject'
Error: Python(MAPCHANGER), Python script error
Traceback (most recent call last):
  File "D:\Blender Foundation\mygame.blend\Doors.py", line 1879, in mapfog
AttributeError: 'PyObjectPlus' object has no attribute 'world'
..................... -> crash game.

Im sure 99%, the bad commit is :  https://github.com/UPBGE/blender/issues/335

**Comment by ondredeniso** [comment]
Im manually join this in my stabled inital 0.1.2 build and got crappy bugs and instant blender crash https://github.com/UPBGE/blender/commit/814afdf57eae0eb284a4ca9d757384857468e51e

**Comment by ondredeniso** [comment]
Now i loose source code, because dont make backup of big x64 Lib folder.

**Comment by panzergame** [comment]
Can you provide an example file ?

**Comment by ondredeniso** [comment]
Is almost completed game, prepared for steam pay) I found time for zip little example.

**Comment by panzergame** [comment]
At least provide me the 20 lines of python around the exception and a description of the libload you made.

**Comment by ondredeniso** [comment]
def SetPosMAPS(cont):
	own = cont.owner
	if own["init"]==False:
		for X in g.LibList():
			g.LibFree(X)
		R.setGLSLMaterialSetting("shadows", g.Rshadows)
		R.setGLSLMaterialSetting("shaders", g.Rshaders)
		R.setGLSLMaterialSetting("extra_textures", g.extra_textures)
		g.hasCamera=False
		g.LibLoad(g.expandPath('//Scenes/mp'+str(g.maps))+'.blend', 'Scene', load_actions=1, load_scripts=1)
		cam=g.getCurrentScene().addObject("CameraSk", own, 0) #line 2185
		cam.worldPosition.z=4600
		print("game started, map is: ", g.maps,)
		g.aControl2 = True
		own["inito"]=True

**Comment by panzergame** [comment]
i have a fix way, i will write it tomorrow.

**Comment by panzergame** [comment]
@ondredeniso : is bfe217cee2bb501e4492562d58a93653e2764117 fixing it ?

**Comment by ondredeniso** [comment]
Fantastic! I should donate u (if i have incoming)
