### ISSUE TITLE
Compiled on OSX, but materials are all white and environment is black

### ISSUE THREAD

**Issue by songproducer** [UPBGE/blender#255]
Here is my console output:

```
Read new prefs: /Users/leotreasure/Library/Application Support/Blender/2.78/config/userpref.blend
2016-10-08 16:32:03.235 blender[3907:971982] Error loading /Library/Audio/Plug-Ins/HAL/JackRouter.plugin/Contents/MacOS/JackRouter:  dlopen(/Library/Audio/Plug-Ins/HAL/JackRouter.plugin/Contents/MacOS/JackRouter, 262): Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /Library/Audio/Plug-Ins/HAL/JackRouter.plugin/Contents/MacOS/JackRouter
  Reason: image not found
2016-10-08 16:32:03.235 blender[3907:971982] Cannot find function pointer New_JackRouterPlugIn for factory 7CB18864-927D-48B5-904C-CCFBCFBC7ADD in CFBundle/CFPlugIn 0x7fbabe58c260 </Library/Audio/Plug-Ins/HAL/JackRouter.plugin> (bundle, not loaded)
found bundled python: /Users/leotreasure/upbge/cmake-cmake/bin/blender.app/Contents/MacOS/../Resources/2.78/python
addon not found: 'io_scene_3ds'
addon not found: 'io_scene_fbx'
addon not found: 'io_anim_bvh'
addon not found: 'io_mesh_ply'
addon not found: 'io_scene_obj'
addon not found: 'io_scene_x3d'
addon not found: 'io_mesh_stl'
addon not found: 'io_mesh_uv_layout'
addon not found: 'io_curve_svg'
addon not found: 'io_scene_dae'
addon not found: 'godot_export_manager'
addon not found: 'add_mesh_extra_objects'
read blend: /Users/leotreasure/Documents/Blender/cubeupbge.blend
GPUShader: compile error:
ERROR: 0:1831: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:1838: Use of undeclared identifier 'depth'

GPUShader: compile error:
ERROR: 0:1831: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:1838: Use of undeclared identifier 'depth'


Blender Game Engine Started
GPUShader: compile error:
ERROR: 0:1831: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:1838: Use of undeclared identifier 'depth'

Blender Game Engine Finished
```

**Comment by youle31** [comment]
@songproducer  have no more error when he removes : 
if (ma->mode & MA_TRANSP && ma->mode2 & MA_DEPTH_TRANSP) {
		GPU_link(mat, "shade_alpha_depth",
				 GPU_builtin(GPU_VIEW_POSITION),
				 GPU_dynamic_texture_ptr(GPU_texture_global_depth_ptr(), GPU_DYNAMIC_SAMPLER_2DBUFFER, ma),
				 shi->alpha, GPU_uniform(&ma->depthtranspfactor), &shr->alpha);
	}
from gpu_material.c and shade_alpha_depth in gpu_shader_material.glsl.

The option depth transparency was not checked in the material tab.

The problem is linked to support of GLSL textureSize function: https://www.opengl.org/sdk/docs/man4/html/textureSize.xhtml

Can we find an alternative to textureSize? uniforms GPU_texture_width and height?

Or can we add a check to prevent this shader to be read?

I don't know how to solve this issue...

**Comment by songproducer** [comment]
Although I don't get any errors now, and environment colours are working - the materials still show only white.

**Comment by significant-bit** [comment]
According to that link the textureSize function is part of GLSL 1.3 / OpenGL 3.0 and Mac only supports GLSL 1.2 / GL 2.1 for now. I'm working on getting all platforms to GLSL 1.5 / GL 3.2 core profile but we're not there yet. See developer.blender.org/T49012

For now a hack like this might work. GLSL:

#if __VERSION__ < 130
uniform vec2 textureSz;
vec2 textureSize(in unusedSampler) {
   return textureSz;
}
#endif

Application code:
Make the node responsible for setting textureSz values if (not GLEW_VERSION_3_0).

Is textureSize called for only one texture or more than one? This hack assumes only one.

**Comment by youle31** [comment]
Thanks very much @significant-bit :) We'll try to do a patch with your hack and ask @songproducer to see if he can test it and confirm that it solves the bug. Thanks for your precious advices!

**Comment by songproducer** [comment]
@youle31 @significant-bit Just saw this now, will try it again today.

**Comment by songproducer** [comment]
I just tried compiling with the latest source again but still same error :(

GPUShader: compile error:
ERROR: 0:1865: Invalid call of undeclared identifier 'textureSize'
ERROR: 0:1872: Use of undeclared identifier 'depth'

**Comment by youle31** [comment]
We haven't fixed the bug yet. I managed to build osx on a virtual machine unfortunately i can't test it because i have no 3d driver on the virtual machine... So i'll see if i Can make triple boot hackintosh, linux, windows but it can take time

**Comment by youle31** [comment]
@panzergame : Do you think something like that: http://pasteall.org/104130/diff could work?

**Comment by panzergame** [comment]
@youle31 : I think it can work if @songproducer have the GL_EXT_gpu_shader4 extension, @songproducer do you have the GL_EXT_gpu_shader4 extension ?

**Comment by songproducer** [comment]
@panzergame How can I see if I have it?

**Comment by panzergame** [comment]
@songproducer if your in linux you can check it with glxinfo, on windows i don't really know.

**Comment by songproducer** [comment]
@panzergame I have a mac. running glxinfo even with commands seems to hang it.

**Comment by lordloki** [comment]
Check this table: https://support.apple.com/en-us/HT202823

2016-11-07 23:21 GMT+01:00 songproducer <notifications@github.com>:

**Comment by youle31** [comment]
@songproducer : I think the better would be to test directly if the patch works for you.

In upbge sources folder, open a terminal, and type:

git reset --hard (In the case you still have the modifs you made last time) 
git pull

Then in XCode open gpu_shader_material.glsl and find shade_alpha_depth shader. Replace it with http://pasteall.org/104502 . Save.

Build upbge.

Test if this works.... A test file for soft particles: http://pasteall.org/blend/index.php?id=44214 (you can enable / disable depth transparency in particle (layer 2) material tab to compare with or without, assuming my patch works :/)

**Comment by youle31** [comment]
:/ the patch doesn't work on my PC portable on Linux with Mesa drivers so bad idea finally... Sorry. Better to forbid this shader as Mike Erwin suggested #if (__VERSION__ < 130)

**Comment by panzergame** [comment]
master branch is now using a other way that textureSize, @songproducer Could you test and close the issue if the issue gone ?
